const seedJobData = [
  {
    id: "e9e632a7-c756-40c9-b1ca-c3eb5c7f9ce3",
    company: "Game Closure",
    title: "Senior Game Engineer (REMOTE)",
    type: "Full Time",
    location: "San Francisco, Mountain View, Tokyo, Remote",
    postedDate: "Sat Aug 03 00:50:23 UTC 2019",
    description: "Game Closure is on the hunt for  Senior Game Engineers to help us build the social games that will be tomorrow’s biggest hits on Facebook", 
    companyURL: "http://gameclosure.com",
    listingURL: "https://jobs.github.com/positions/e9e632a7-c756-40c9-b1ca-c3eb5c7f9ce3",
  },
  {
    id: "0b183e14-9064-44cb-afa1-52585b124ed2",
    company: "GetThru",
    title: "Vice President of Engineering",
    type: "Full Time",
    location: "Remote",
    postedDate: "Tue Mar 31 19:05:41 UTC 2020",
    description: "<p>GetThru is hiring a Vice President of Engineering to define and drive the technical strategy, architectural vision, and development methodology for our software-as-a-service products.\nThe VP of Engineering will instill the structure and processes necessary to build high quality software while maintaining the flexibility needed for a rapidly growing, entrepreneurial enterprise.",
    companyURL: "http://www.getthru.io",
    listingURL: "https://jobs.github.com/positions/0b183e14-9064-44cb-afa1-52585b124ed2",
  },
  {
    id: "051f00e9-068c-47b8-a85a-674a626eff17",
    company: "Gorgias",
    title: "Full-Stack Engineer",
    type: "Full Time",
    location: "Paris and San Francisco",
    postedDate: "Thu Mar 19 17:57:51 UTC 2020",
    description: "<p>We created the company in Paris and are now a San Francisco based startup with a newly opened Paris office. We're making a SaaS helpdesk that automates a big part of the repetitive customer support tasks. We're close to 2000+ paying companies using our product and growing fast.",
    companyURL: "https://www.gorgias.com/",
    listingURL: "https://jobs.github.com/positions/051f00e9-068c-47b8-a85a-674a626eff17",
  },
  {
  id: "0111dd85-71cd-45e3-972c-023b152005d6",
  company: "Triplebyte",
  title: "Full Stack Engineer",
  type: "Full Time",
  location: "San Francisco or Remote",
  postedDate: "Wed Mar 18 23:23:32 UTC 2020",
  description: "<h3>About Triplebyte</h3>\n<p>Triplebyte is transforming the way software engineers are hired. Our mission is to build an open, valuable and skills-based credential for all engineers. This is important because millions of people have skills (and deserve good jobs), but don’t fit the profile that recruiters seek. Another way of saying this is that talent is uniformly distributed, but opportunity is not. Our goal is to broaden the distribution of opportunity.",
  companyURL: "http://www.triplebyte.com",
  listingURL: "https://jobs.github.com/positions/0111dd85-71cd-45e3-972c-023b152005d6",
  },
]

export default seedJobData;